export const loginConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  LOGOUT: "USER_LOGOUT",
  GETALL_SUCCESS: "GETALL_USERS_SUCCESS",
  FILTER_USERS: "FILTER_USERS",
  RESET_FILTER: "RESET_FILTER",
};
